# Generated by Django 4.0.1 on 2022-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ ها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
