# Generated by Django 4.0.1 on 2022-02-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
