# Generated by Django 4.0.1 on 2022-02-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
