# Generated by Django 4.0.1 on 2022-02-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'verbose_name': 'آی پی', 'verbose_name_plural': 'آی پی ها'},
        ),
    ]
